// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using baseapi.Models;

#nullable disable

namespace baseapi.Migrations
{
    [DbContext(typeof(BaseapiContext))]
    [Migration("20241209154203_DTO")]
    partial class DTO
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("baseapi.Models.Selection", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "category");

                    b.Property<bool>("IsBookmarked")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "isBookmarked");

                    b.Property<bool>("IsTrending")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "isTrending");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "rating");

                    b.Property<string>("Thumbnail_regular_large")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "thumbnail.regular.large");

                    b.Property<string>("Thumbnail_regular_medium")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "thumbnail.regular.medium");

                    b.Property<string>("Thumbnail_regular_small")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "thumbnail.regular.small");

                    b.Property<string>("Thumbnail_trending_large")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "thumbnail.trending.large");

                    b.Property<string>("Thumbnail_trending_small")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "thumbnail.trending.small");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "title");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "year");

                    b.HasKey("Id");

                    b.ToTable("Selections");
                });
#pragma warning restore 612, 618
        }
    }
}
