// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using baseapi.Data;

#nullable disable

namespace base_api.Migrations
{
    [DbContext(typeof(BaseapiContext))]
    partial class BaseapiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("baseapi.Models.Regular", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Large")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Medium")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Small")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Regulars");
                });

            modelBuilder.Entity("baseapi.Models.Selection", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsBookmarked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTrending")
                        .HasColumnType("boolean");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ThumbnailId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ThumbnailId");

                    b.ToTable("Selections");
                });

            modelBuilder.Entity("baseapi.Models.Thumbnail", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("RegularId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TrendingId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RegularId");

                    b.HasIndex("TrendingId");

                    b.ToTable("Thumbnails");
                });

            modelBuilder.Entity("baseapi.Models.Trending", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Large")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Small")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Trendings");
                });

            modelBuilder.Entity("baseapi.Models.Selection", b =>
                {
                    b.HasOne("baseapi.Models.Thumbnail", "Thumbnail")
                        .WithMany()
                        .HasForeignKey("ThumbnailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Thumbnail");
                });

            modelBuilder.Entity("baseapi.Models.Thumbnail", b =>
                {
                    b.HasOne("baseapi.Models.Regular", "Regular")
                        .WithMany()
                        .HasForeignKey("RegularId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("baseapi.Models.Trending", "Trending")
                        .WithMany()
                        .HasForeignKey("TrendingId");

                    b.Navigation("Regular");

                    b.Navigation("Trending");
                });
#pragma warning restore 612, 618
        }
    }
}
